// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://dkgsqkprdpgydybxcwhj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRrZ3Nxa3ByZHBneWR5Ynhjd2hqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA5NzM0MzcsImV4cCI6MjA3NjU0OTQzN30.NioYL-fuwzTD1Z9C46QSdukeZaAEv01JjSea3JeaRLY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);